---
- name: module demo 
  hosts: localhost
  become: yes
  tasks: 
    - name: adds nauticus to logs
      become: yes
      become_method: sudo
      cron: 
        name: "test"
        user: "ubuntu"
        state: present
        minute: "*/1"
        hour: "*"
        day: "*"
        month: "*"  
        job: 'logger "nauticus"' 

    - name: apt-get update
      apt:
        update-cache: yes
      changed_when: 0

    - name: installs Htop
      command: apt install htop

    
