- name: cron module demo 
  hosts: localhost
  become: yes
  tasks: 
    - name: adds nauticus to logs
      become: yes
      become_method: sudo
      cron: 
        name: "test"
        user: "ubuntu"
        state: present
        minute: "*/1"
        hour: "*"
        day: "*"
        month: "*"  
        job: 'logger "nauticus"' 

    - name: Updates packages
      become: yes
      become_method: sudo
      cron:
        name: "update"
        user: "ubuntu"
        weekday: "1-7"
        minute: "0"
        hour: "19"
        job: "/usr/bin/apt update -q -y"
        state: present

    #
    # Add upgrade cron
    #
    - name: Upgrades packages 
      become: yes
      become_method: sudo
      cron:
        name: "upgrade"
        user: "ubuntu"
        weekday: "1-7"
        minute: "0"
        hour: "20"
        job: "/usr/bin/apt upgrade -q -y"
        state: present

    #
    # Add autoclean cron
    #
    - name: Autoclean packages
      become: yes
      become_method: sudo
      cron:
        name: "autoclean"
        user: "ubuntu"
        weekday: "1-7"
        minute: "0"
        hour: "23"
        job: "/usr/bin/apt autoclean"
        state: present

     #
    # Adds htop
    #
    - name: Install Htop
      become: yes
      become_method: sudo
      cron:
        name: "htopinstall"
        special_time: "monthly"  
        user: "ubuntu"
        job: "/usr/bin/apt install htop"
        state: present
